services:
  web:
    image: flask-app:latest
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]